// AUTO-GENERATED by scripts/analyze-topics.ts
// 2026-04-14T19:52:34.780Z
//
// Review this file carefully, then replace lib/topics.ts when satisfied.
// Full analysis: scripts/topic-analysis-report.md
//
// Persona confidence: medium
// The persona weights are based on the frequency and sentiment of the reviews. The confidence is medium due to the limited number of reviews for some personas.

export interface Topic {
  id: string;
  label: string;
  keywords: string[];
  amenityKeys: string[]; // amenity keywords that make this topic relevant to a property
  ratingKeys: string[];  // structured sub-rating field names from Review.rating
}

export const TOPICS: Topic[] = [
  {
    "id": "cleanliness",
    "label": "Cleanliness",
    "keywords": [
      "clean rooms",
      "disgusting",
      "dirty",
      "moldy",
      "not clean",
      "leftover food",
      "dust",
      "smelly bathroom",
      "stains",
      "cracked",
      "not maintained",
      "trash on the floor",
      "hair in the shower",
      "black spots",
      "clean but missing extras",
      "not cleaned"
    ],
    "amenityKeys": [],
    "ratingKeys": [
      "roomcleanliness"
    ]
  },
  {
    "id": "location",
    "label": "Location & Neighborhood",
    "keywords": [
      "great location",
      "close to activities",
      "next to train station",
      "busy part of town",
      "near restaurants",
      "convenient location",
      "close to the beach",
      "not safe at night",
      "hard to maneuver with luggage",
      "close to shopping",
      "good for visiting",
      "near gas station",
      "in a terrible area",
      "near the interstate",
      "close to attractions"
    ],
    "amenityKeys": [],
    "ratingKeys": [
      "convenienceoflocation"
    ]
  },
  {
    "id": "food_breakfast",
    "label": "Food & Breakfast",
    "keywords": [
      "no breakfast included",
      "good meal options",
      "breakfast room small",
      "average breakfast",
      "not offered",
      "breakfast was great",
      "good food",
      "no food service",
      "breakfast was not the same",
      "limited dining options",
      "breakfast buffet",
      "no coffee",
      "food was terrible",
      "breakfast area crowded",
      "not enough seating"
    ],
    "amenityKeys": [
      "breakfast"
    ],
    "ratingKeys": []
  },
  {
    "id": "wifi_internet",
    "label": "WiFi & Internet",
    "keywords": [
      "poor wifi",
      "no internet",
      "wifi not working",
      "limited wifi",
      "internet pathetic",
      "no phone service",
      "wifi issues",
      "unsecured network",
      "no connectivity",
      "internet down",
      "no cable tv",
      "slow internet",
      "wifi signal weak",
      "no access",
      "no hot water"
    ],
    "amenityKeys": [
      "wifi"
    ],
    "ratingKeys": [
      "communication"
    ]
  },
  {
    "id": "parking",
    "label": "Parking",
    "keywords": [
      "no parking",
      "horrendous parking",
      "not enough spots",
      "parked at gas station",
      "parking arrangements off site",
      "complicated parking",
      "free parking",
      "private parking garage",
      "parking lot",
      "hard to find parking",
      "no parking available",
      "parking issues",
      "limited parking",
      "parking was a hassle"
    ],
    "amenityKeys": [
      "parking"
    ],
    "ratingKeys": []
  },
  {
    "id": "checkin_checkout",
    "label": "Check-in & Check-out",
    "keywords": [
      "check-in was quick",
      "rude check-in",
      "check-in not until 3",
      "system was down",
      "check-in process",
      "late check-in",
      "check-out was a hassle",
      "check-in issues",
      "no greeting at check-in",
      "no assistance at check-in",
      "check-in experience",
      "check-in staff",
      "check-in delay",
      "check-in confusion"
    ],
    "amenityKeys": [],
    "ratingKeys": [
      "checkin"
    ]
  },
  {
    "id": "noise",
    "label": "Noise & Quiet",
    "keywords": [
      "very noisy",
      "traffic noise",
      "loud",
      "noisy at night",
      "could hear talking",
      "thin walls",
      "loud guests",
      "noise from hallway",
      "noise from street",
      "loud chimes",
      "no soundproofing",
      "could hear everything",
      "noisy neighbors",
      "noise complaints",
      "loud music"
    ],
    "amenityKeys": [],
    "ratingKeys": []
  },
  {
    "id": "room_comfort",
    "label": "Room Size & Comfort",
    "keywords": [
      "uncomfortable room",
      "small room",
      "not comfortable",
      "bed was hard",
      "room size",
      "room was hot",
      "room was dated",
      "noisy room",
      "poor ventilation",
      "hard to sleep",
      "room was cozy",
      "room amenities",
      "room cleanliness",
      "room temperature",
      "room layout"
    ],
    "amenityKeys": [],
    "ratingKeys": [
      "roomcomfort",
      "hotelcondition",
      "roomquality"
    ]
  },
  {
    "id": "bathroom",
    "label": "Bathroom",
    "keywords": [
      "bathroom was dirty",
      "mold in bathroom",
      "shower not clean",
      "toilet issues",
      "bathroom lights flickered",
      "no hot water",
      "bathroom needs updating",
      "smelly bathroom",
      "broken shower head",
      "bathroom decor",
      "toilet wouldn't flush",
      "bathroom cleanliness",
      "bathroom size",
      "bathroom amenities",
      "bathroom maintenance"
    ],
    "amenityKeys": [],
    "ratingKeys": []
  },
  {
    "id": "staff_service",
    "label": "Staff & Service",
    "keywords": [
      "friendly staff",
      "rude staff",
      "helpful staff",
      "staff was unhelpful",
      "staff not available",
      "staff was excellent",
      "staff was accommodating",
      "poor service",
      "staff issues",
      "staff at front desk",
      "staff interaction",
      "staff responsiveness",
      "staff was nice",
      "staff was cold",
      "staff assistance"
    ],
    "amenityKeys": [],
    "ratingKeys": [
      "service"
    ]
  },
  {
    "id": "value",
    "label": "Value for Money",
    "keywords": [
      "not worth the price",
      "good value",
      "affordable",
      "overpriced",
      "poor value for money",
      "value for the price",
      "not worth it",
      "expensive for what you get",
      "price was reasonable",
      "good deal",
      "value compared to others",
      "value for stay",
      "price vs quality",
      "price was high",
      "value for amenities"
    ],
    "amenityKeys": [],
    "ratingKeys": [
      "valueformoney"
    ]
  }
];

export function classifyText(text: string): Set<string> {
  if (!text) return new Set();
  const lower = text.toLowerCase();
  const matched = new Set<string>();
  for (const topic of TOPICS) {
    for (const kw of topic.keywords) {
      if (lower.includes(kw)) {
        matched.add(topic.id);
        break;
      }
    }
  }
  return matched;
}

export function getTopicById(id: string): Topic | undefined {
  return TOPICS.find((t) => t.id === id);
}

// ── Persona weights ──────────────────────────────────────────────────────────
// Derived empirically from 150 sampled reviews.
// Values are multipliers on gap scores when selecting follow-up questions.
//   1.0 = neutral   >1.0 = this persona cares more   <1.0 = cares less
//
// Confidence: medium

export type PersonaType = "business" | "family" | "couple" | "solo";

export const PERSONA_WEIGHTS: Record<PersonaType, Record<string, number>> =
{
  "business": {
    "cleanliness": 1.5,
    "location": 1.3,
    "food_breakfast": 1,
    "wifi_internet": 2,
    "parking": 1.2,
    "checkin_checkout": 1.4,
    "noise": 1,
    "room_comfort": 1.5,
    "bathroom": 1.1,
    "staff_service": 1.4,
    "value": 1.3
  },
  "family": {
    "cleanliness": 1.8,
    "location": 2,
    "food_breakfast": 1.5,
    "wifi_internet": 1,
    "parking": 1.2,
    "checkin_checkout": 1.3,
    "noise": 1.4,
    "room_comfort": 2,
    "bathroom": 1.6,
    "staff_service": 1.5,
    "value": 1.7
  },
  "couple": {
    "cleanliness": 1.4,
    "location": 1.8,
    "food_breakfast": 1.5,
    "wifi_internet": 1,
    "parking": 1.1,
    "checkin_checkout": 1.3,
    "noise": 1.2,
    "room_comfort": 1.7,
    "bathroom": 1.4,
    "staff_service": 1.6,
    "value": 1.5
  },
  "solo": {
    "cleanliness": 1.6,
    "location": 1.5,
    "food_breakfast": 1,
    "wifi_internet": 2,
    "parking": 1,
    "checkin_checkout": 1.2,
    "noise": 1.3,
    "room_comfort": 1.4,
    "bathroom": 1.1,
    "staff_service": 1.5,
    "value": 1.3
  }
};
